//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBindingDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSession
    {
        public long RollNumber { get; set; }
        public long StudentID { get; set; }
        public long ClassID { get; set; }
        public long SessionID { get; set; }
        public long TeacherID { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Session Session { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Student Student { get; set; }
    }
}
