//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBindingD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAttendance
    {
        public long EmployeeAttendanceID { get; set; }
        public long EmployeeID { get; set; }
        public long SessionID { get; set; }
        public long AttendanceDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Session Session { get; set; }
    }
}
