//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBindingD
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeDetail
    {
        public long FeeDetailID { get; set; }
        public long PaidFee { get; set; }
        public string PaidDate { get; set; }
        public long StudentID { get; set; }
        public long PaidForMonth { get; set; }
        public long Arrears { get; set; }
        public long SessionID { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Session Session { get; set; }
    }
}
